# vich_uploader:
#     db_driver: orm

vich_uploader:
    db_driver: orm        # or mongodb or phpcr - default db driver
    twig: true            # set to false to disable twig integration
    form: true            # set to false to disable form integration
    storage: file_system  # or gaufrette or flysystem  

    metadata:
        type: attribute
        auto_detection: true
        cache: file
        
    mappings:
        galerie_images:
            uri_prefix: '%galerie_images%'
            upload_destination: '%kernel.project_dir%/public%galerie_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: false
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
